name: Daily update

on:
  schedule:
  - cron: "17 10 * * *"
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
    - name: crane-installer
      uses: IAreKyleW00t/crane-installer@v1.3
            
    - name: copy
      shell: bash
      run: |
        crane auth login quay.io -u "${{ secrets.QUAY_USERNAME }}" -p "${{ secrets.QUAY_PASSWORD }}"
        crane-copy () {
            crane copy $1 quay.io/dhcr/$1 --platform linux/amd64
        }
        crane-copy eclipse-temurin:8-jre
        crane-copy eclipse-temurin:8-jdk
        crane-copy eclipse-temurin:11-jre
        crane-copy eclipse-temurin:11-jdk
        crane-copy eclipse-temurin:17-jre
        crane-copy eclipse-temurin:17-jdk
        crane-copy eclipse-temurin:21-jre
        crane-copy eclipse-temurin:21-jdk
        crane-copy node:16-alpine
        crane-copy node:18-alpine
