on:
  schedule:
  - cron: "17 10 * * *"
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest

    permissions:
      issues: write

    steps:
    - name: crane-installer
      uses: IAreKyleW00t/crane-installer@v1.3
            
    - name: copy
      shell: bash
      run: |
        crane auth login quay.io -u "${{ secrets.QUAY_USERNAME }}" -p "${{ secrets.QUAY_PASSWORD }}"
        crane-copy () {
            crane copy $1 quay.io/dhcr/$1 --platform linux/amd64
        }
        crane-copy node:18-alpine
